{
 "title": "ODF",
 "description": "odf dashboard",
 "tags": [ "Openshift" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "job",
    "query": {
     "query": "label_values(odf_system_health_status{cluster=\"$cluster\"}, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ODF Health State",
   "type": "stat",
   "description": "ODF Health State",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "odf_system_health_status{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "ODF Utilization",
   "type": "gauge",
   "description": "ODF Utilization",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(odf_system_raw_capacity_used_bytes{cluster=\"$cluster\",job=\"rook-ceph-mgr\"})/sum(odf_system_raw_capacity_total_bytes{cluster=\"$cluster\",job=\"rook-ceph-mgr\"})*100"
    }
   ]
  },
  {
   "title": "Total ODF Size (TB)",
   "type": "stat",
   "description": "Total ODF Size (TB)",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(odf_system_raw_capacity_total_bytes{cluster=\"$cluster\",job=\"rook-ceph-mgr\"})"
    }
   ]
  },
  {
   "title": "Total Used Storage",
   "type": "timeseries",
   "description": "Total Used Storage",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(odf_system_raw_capacity_used_bytes{cluster=\"$cluster\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "ODF IOPs",
   "type": "timeseries",
   "description": "ODF IOPs",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(odf_system_iops_total_bytes{cluster=\"$cluster\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(odf_system_throughput_total_bytes{cluster=\"$cluster\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "ODF Latency",
   "type": "timeseries",
   "description": "ODF Latency",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(odf_system_latency_seconds{cluster=\"$cluster\"})"
    }
   ]
  }
 ]
}