{
 "title": "ACS",
 "description": "acs dashboard",
 "tags": [ "Openshift" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(rox_central_node_scan_num_components{}, ClusterName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RHACS Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rox_central_info{}" }
   ]
  },
  {
   "title": "RHACS Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rox_central_uptime_seconds{}" }
   ]
  },
  {
   "title": "Total Number of Secured Clusters",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group(rox_central_node_scan_num_components{}) by (ClusterName))"
    }
   ]
  },
  {
   "title": "Total Number of Nodes Secured by RHACS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group(rox_central_node_scan_num_components{}) by (NodeName))"
    }
   ]
  },
  {
   "title": "Total Number of Nodes/Secured  Cluster by RHACS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group(rox_central_node_scan_num_components{ClusterName=\"$cluster\"}) by (NodeName))"
    }
   ]
  },
  {
   "title": "Total Number of vCPUs secured by RHACS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rox_central_secured_vcpus{})"
    }
   ]
  }
 ]
}