kind: ConfigMap
apiVersion: v1
metadata:
  name: observability-metrics-odf-allowlist 
  Namespace: open-cluster-management-observability
data:
  metrics_list.yaml: |
    names:
      - -odf_system_raw_capacity_total_bytes
      - -odf_system_raw_capacity_used_bytes
      - -odf_system_iops_total_bytes
      - -odf_system_latency_seconds
